name: mh-data

on:
  workflow_dispatch:
  schedule:
    - cron: '40 6 1 * *'

permissions:
  contents: write

jobs:
  get-mh-datas:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - uses: allenevans/set-env@v2.0.0
        with:
          ZL_ROLEID: ${{secrets.ZL_ROLEID}}
          ZL_SERVERID: ${{secrets.ZL_SERVERID}}
          SEND_KEY: ${{secrets.SEND_KEY}}
          BARK_KEY: ${{secrets.BARK_KEY}}
          TOKEN: ${{secrets.TOKEN}}

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable
      - run: chrome --version

      - name: Install Deps
        run: pnpm install --no-frozen-lockfile

      - name: Install Chromium
        run: node node_modules/puppeteer/install.js

      - name: Run
        run: pnpm run action:mhdata

      - name: Git push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git pull
          git add .
          git commit -m 'update(MH): 武器数据'
          git push
